### ISSUE TITLE
Deleting a project: how should that look?

### ISSUE THREAD

**Issue by hfaste** [CreativityKernel/FirstLaunch#24]
Add an "X" button on projects somehow that allows us to delete them (for MVP purposes), and design how that looks. After we've reviewed it, update the dev ticket for this task so Piyum knows what it should look like.

**Comment by SongXuan5754** [comment]
![delete a project](https://user-images.githubusercontent.com/16970285/48171056-1092a400-e2af-11e8-8d21-50cb36dd73e1.png)

**Comment by SongXuan5754** [comment]
![delete a project](https://user-images.githubusercontent.com/16970285/48172170-af210400-e2b3-11e8-8614-64e0fda07b09.png)
![confirm to delete a project](https://user-images.githubusercontent.com/16970285/48172173-b0eac780-e2b3-11e8-841c-f0dd1f0e4f61.png)

**Comment by SongXuan5754** [comment]
@hfaste I would like to know which one works better.
