### ISSUE TITLE
Edit project: how should that look?

### ISSUE THREAD

**Issue by hfaste** [CreativityKernel/FirstLaunch#25]
If a user wants to edit a project description, how should that look? Design how that looks. After we've reviewed it, update the dev ticket for this task so Piyum knows what it should look like.

**Comment by SongXuan5754** [comment]
![edit the project](https://user-images.githubusercontent.com/16970285/48172246-fc9d7100-e2b3-11e8-9010-d40c24358ddd.png)

**Comment by SongXuan5754** [comment]
![edit this project](https://user-images.githubusercontent.com/16970285/48172272-1b9c0300-e2b4-11e8-9199-c4f68a4bfad3.png)

**Comment by SongXuan5754** [comment]
![edit the project](https://user-images.githubusercontent.com/16970285/48172318-4ab27480-e2b4-11e8-9338-4902bc196034.png)

**Comment by SongXuan5754** [comment]
![edit delete the project](https://user-images.githubusercontent.com/16970285/48172455-cb717080-e2b4-11e8-81d0-0ef68563ac23.png)
