### ISSUE TITLE
Delete/edit idea: how should that look?

### ISSUE THREAD

**Issue by hfaste** [CreativityKernel/FirstLaunch#26]
For prototype MVP purposes we will need to delete lots of the old/ugly ideas to curate our idea set and make sure it looks good. Rather than putting an X on every idea, there's a button somewhere that allows users to enter "cleanup mode" to delete lots of ideas all at once, and then confirm?

We also need a way to edit existing ideas (to fix Typos, make them better, etc.). How should that look?

**Comment by SongXuan5754** [comment]
![edit delete the project](https://user-images.githubusercontent.com/16970285/48172421-ac72de80-e2b4-11e8-8f88-a6b72a6f8aef.png)
