### ISSUE TITLE
Cursor on All Projects page

### ISSUE THREAD

**Issue by hfaste** [CreativityKernel/FirstLaunch#3]
In the All Projects page, whenever I roll the cursor over text it changes from an arrow to the "insert text" cursor. This doesn't feel right if I'm then going to click (e.g. to take me into a project). Can we keep the cursor as an arrow (e.g. mac equivalent of the left-most cursor in this image)?:

![inter-mouse-image1](https://user-images.githubusercontent.com/1205103/46578248-bbadf600-c9af-11e8-9576-86be89d602f0.png)

**Comment by rexpiyum** [comment]
added **user-select: none;** to **project-card** CSS class
