### ISSUE TITLE
(Links issue)View button- Individual project page 

### ISSUE THREAD

**Issue by SongXuan5754** [CreativityKernel/FirstLaunch#8]
View button doesn't work, because nobody has designed what "viewing" a project will look like. So we need to design that before we can have the dev team create a link to the viewed destination (e.g. opportunity page, Likes and Wishes page, Cheatstorming, etc.). This is heavily related to online LEARNING.

Note: in the spec document, the only options are "START" and "VIEW".

<img width="880" alt="screen shot 2018-10-08 at 2 39 23 pm" src="https://user-images.githubusercontent.com/16970285/46635088-03e02c00-cb08-11e8-8343-320f973d528a.png">

**Comment by SongXuan5754** [comment]
<img width="960" alt="screen shot 2018-10-09 at 5 32 13 pm" src="https://user-images.githubusercontent.com/16970285/46706454-68bf8300-cbe9-11e8-9875-16d36dab5d30.png">

**Comment by hfaste** [comment]
For now, I would be tempted to either make "VIEW" greyed out, or get rid of VIEW all together for the Beta release.

**Comment by rexpiyum** [comment]
got rid of view for now!
